/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("reviews").del();
  await knex("reviews").insert([
    {
      id: 1,
      productId: 78,
      userId: 1,
      rating: 5,
      comment: "Would buy again!",
      reviewerName: "Hunter Gordon",
      reviewerEmail: "hunter.gordon@x.dummyjson.com",
    },
    {
      id: 2,
      productId: 78,
      userId: 1,
      rating: 5,
      comment: "Would buy again!",
      reviewerName: "Emma Wilson",
      reviewerEmail: "emma.wilson@x.dummyjson.com",
    },
    {
      id: 3,
      productId: 78,
      userId: 1,
      rating: 5,
      comment: "Very pleased!",
      reviewerName: "David Martinez",
      reviewerEmail: "david.martinez@x.dummyjson.com",
    },

    {
      id: 4,
      productId: 79,
      userId: 1,
      rating: 5,
      comment: "Very satisfied!",
      reviewerName: "Jack Ward",
      reviewerEmail: "jack.ward@x.dummyjson.com",
    },
    {
      id: 5,
      productId: 79,
      userId: 1,
      rating: 1,
      comment: "Very disappointed!",
      reviewerName: "Ava Harris",
      reviewerEmail: "ava.harris@x.dummyjson.com",
    },
    {
      id: 6,
      productId: 79,
      userId: 1,
      rating: 5,
      comment: "Great value for money!",
      reviewerName: "Brayden Fleming",
      reviewerEmail: "brayden.fleming@x.dummyjson.com",
    },

    {
      id: 7,
      productId: 80,
      userId: 1,
      rating: 4,
      comment: "Great value for money!",
      reviewerName: "Samantha Howard",
      reviewerEmail: "samantha.howard@x.dummyjson.com",
    },
    {
      id: 8,
      productId: 80,
      userId: 1,
      rating: 2,
      comment: "Would not buy again!",
      reviewerName: "Daniel Cook",
      reviewerEmail: "daniel.cook@x.dummyjson.com",
    },
    {
      id: 9,
      productId: 80,
      userId: 1,
      rating: 5,
      comment: "Very satisfied!",
      reviewerName: "Brayden Fleming",
      reviewerEmail: "brayden.fleming@x.dummyjson.com",
    },

    {
      id: 10,
      productId: 81,
      userId: 1,
      rating: 4,
      comment: "Very happy with my purchase!",
      reviewerName: "Paisley Bell",
      reviewerEmail: "paisley.bell@x.dummyjson.com",
    },
    {
      id: 11,
      productId: 81,
      userId: 1,
      rating: 4,
      comment: "Very pleased!",
      reviewerName: "Lincoln Kelly",
      reviewerEmail: "lincoln.kelly@x.dummyjson.com",
    },
    {
      id: 12,
      productId: 81,
      userId: 1,
      rating: 4,
      comment: "Great product!",
      reviewerName: "Luna Russell",
      reviewerEmail: "luna.russell@x.dummyjson.com",
    },

    {
      id: 13,
      productId: 82,
      userId: 1,
      rating: 3,
      comment: "Very disappointed!",
      reviewerName: "Julian Newton",
      reviewerEmail: "julian.newton@x.dummyjson.com",
    },
    {
      id: 14,
      productId: 82,
      userId: 1,
      rating: 4,
      comment: "Very pleased!",
      reviewerName: "Grace Perry",
      reviewerEmail: "grace.perry@x.dummyjson.com",
    },
    {
      id: 15,
      productId: 82,
      userId: 1,
      rating: 5,
      comment: "Great product!",
      reviewerName: "Daniel Taylor",
      reviewerEmail: "daniel.taylor@x.dummyjson.com",
    },

    {
      id: 16,
      productId: 121,
      userId: 1,
      rating: 4,
      comment: "Highly impressed!",
      reviewerName: "Wyatt Perry",
      reviewerEmail: "wyatt.perry@x.dummyjson.com",
    },
    {
      id: 17,
      productId: 121,
      userId: 1,
      rating: 5,
      comment: "Awesome product!",
      reviewerName: "Olivia Anderson",
      reviewerEmail: "olivia.anderson@x.dummyjson.com",
    },
    {
      id: 18,
      productId: 121,
      userId: 1,
      rating: 4,
      comment: "Highly recommended!",
      reviewerName: "Mateo Nguyen",
      reviewerEmail: "mateo.nguyen@x.dummyjson.com",
    },

    {
      id: 19,
      productId: 122,
      userId: 1,
      rating: 5,
      comment: "Would buy again!",
      reviewerName: "Nicholas Bailey",
      reviewerEmail: "nicholas.bailey@x.dummyjson.com",
    },
    {
      id: 20,
      productId: 122,
      userId: 1,
      rating: 5,
      comment: "Great product!",
      reviewerName: "Clara Berry",
      reviewerEmail: "clara.berry@x.dummyjson.com",
    },
    {
      id: 21,
      productId: 122,
      userId: 1,
      rating: 3,
      comment: "Not as described!",
      reviewerName: "Gavin Stanley",
      reviewerEmail: "gavin.stanley@x.dummyjson.com",
    },

    {
      id: 22,
      productId: 123,
      userId: 1,
      rating: 5,
      comment: "Highly impressed!",
      reviewerName: "Aria Roberts",
      reviewerEmail: "aria.roberts@x.dummyjson.com",
    },
    {
      id: 23,
      productId: 123,
      userId: 1,
      rating: 4,
      comment: "Great product!",
      reviewerName: "Ryan Graham",
      reviewerEmail: "ryan.graham@x.dummyjson.com",
    },
    {
      id: 24,
      productId: 123,
      userId: 1,
      rating: 2,
      comment: "Poor quality!",
      reviewerName: "Mason Wright",
      reviewerEmail: "mason.wright@x.dummyjson.com",
    },

    {
      id: 25,
      productId: 124,
      userId: 1,
      rating: 1,
      comment: "Very unhappy with my purchase!",
      reviewerName: "Eleanor Tyler",
      reviewerEmail: "eleanor.tyler@x.dummyjson.com",
    },
    {
      id: 26,
      productId: 124,
      userId: 1,
      rating: 5,
      comment: "Very satisfied!",
      reviewerName: "Maya Reed",
      reviewerEmail: "maya.reed@x.dummyjson.com",
    },
    {
      id: 27,
      productId: 124,
      userId: 1,
      rating: 4,
      comment: "Fast shipping!",
      reviewerName: "Elena Baker",
      reviewerEmail: "elena.baker@x.dummyjson.com",
    },

    {
      id: 28,
      productId: 125,
      userId: 1,
      rating: 2,
      comment: "Not worth the price!",
      reviewerName: "Owen Fisher",
      reviewerEmail: "owen.fisher@x.dummyjson.com",
    },
    {
      id: 29,
      productId: 125,
      userId: 1,
      rating: 4,
      comment: "Fast shipping!",
      reviewerName: "Jack Ward",
      reviewerEmail: "jack.ward@x.dummyjson.com",
    },
    {
      id: 30,
      productId: 125,
      userId: 1,
      rating: 2,
      comment: "Very dissatisfied!",
      reviewerName: "Nora Mills",
      reviewerEmail: "nora.mills@x.dummyjson.com",
    },

    {
      id: 31,
      productId: 126,
      userId: 1,
      rating: 4,
      comment: "Would buy again!",
      reviewerName: "Benjamin Foster",
      reviewerEmail: "benjamin.foster@x.dummyjson.com",
    },
    {
      id: 32,
      productId: 126,
      userId: 1,
      rating: 5,
      comment: "Very pleased!",
      reviewerName: "Lillian Bishop",
      reviewerEmail: "lillian.bishop@x.dummyjson.com",
    },
    {
      id: 33,
      productId: 126,
      userId: 1,
      rating: 3,
      comment: "Would not recommend!",
      reviewerName: "Harper Garcia",
      reviewerEmail: "harper.garcia@x.dummyjson.com",
    },

    {
      id: 34,
      productId: 127,
      userId: 1,
      rating: 2,
      comment: "Would not buy again!",
      reviewerName: "Penelope Harper",
      reviewerEmail: "penelope.harper@x.dummyjson.com",
    },
    {
      id: 35,
      productId: 127,
      userId: 1,
      rating: 4,
      comment: "Very satisfied!",
      reviewerName: "Nathan Reed",
      reviewerEmail: "nathan.reed@x.dummyjson.com",
    },
    {
      id: 36,
      productId: 127,
      userId: 1,
      rating: 5,
      comment: "Very happy with my purchase!",
      reviewerName: "Madison Stewart",
      reviewerEmail: "madison.stewart@x.dummyjson.com",
    },

    {
      id: 37,
      productId: 128,
      userId: 1,
      rating: 5,
      comment: "Very happy with my purchase!",
      reviewerName: "Ava Harrison",
      reviewerEmail: "ava.harrison@x.dummyjson.com",
    },
    {
      id: 38,
      productId: 128,
      userId: 1,
      rating: 3,
      comment: "Waste of money!",
      reviewerName: "Sophia Brown",
      reviewerEmail: "sophia.brown@x.dummyjson.com",
    },
    {
      id: 39,
      productId: 128,
      userId: 1,
      rating: 5,
      comment: "Great product!",
      reviewerName: "Grace Perry",
      reviewerEmail: "grace.perry@x.dummyjson.com",
    },

    {
      id: 40,
      productId: 129,
      userId: 1,
      rating: 4,
      comment: "Highly recommended!",
      reviewerName: "Benjamin Foster",
      reviewerEmail: "benjamin.foster@x.dummyjson.com",
    },
    {
      id: 41,
      productId: 129,
      userId: 1,
      rating: 4,
      comment: "Very satisfied!",
      reviewerName: "Madison Collins",
      reviewerEmail: "madison.collins@x.dummyjson.com",
    },
    {
      id: 42,
      productId: 129,
      userId: 1,
      rating: 5,
      comment: "Fast shipping!",
      reviewerName: "Emily Johnson",
      reviewerEmail: "emily.johnson@x.dummyjson.com",
    },

    {
      id: 43,
      productId: 130,
      userId: 1,
      rating: 5,
      comment: "Awesome product!",
      reviewerName: "Hannah Howard",
      reviewerEmail: "hannah.howard@x.dummyjson.com",
    },
    {
      id: 44,
      productId: 130,
      userId: 1,
      rating: 1,
      comment: "Would not recommend!",
      reviewerName: "Claire Foster",
      reviewerEmail: "claire.foster@x.dummyjson.com",
    },
    {
      id: 45,
      productId: 130,
      userId: 1,
      rating: 1,
      comment: "Very dissatisfied!",
      reviewerName: "Nora Russell",
      reviewerEmail: "nora.russell@x.dummyjson.com",
    },

    {
      id: 46,
      productId: 131,
      userId: 1,
      rating: 5,
      comment: "Would buy again!",
      reviewerName: "Jace Smith",
      reviewerEmail: "jace.smith@x.dummyjson.com",
    },
    {
      id: 47,
      productId: 131,
      userId: 1,
      rating: 4,
      comment: "Would buy again!",
      reviewerName: "Ruby Andrews",
      reviewerEmail: "ruby.andrews@x.dummyjson.com",
    },
    {
      id: 48,
      productId: 131,
      userId: 1,
      rating: 5,
      comment: "Great value for money!",
      reviewerName: "Aria Roberts",
      reviewerEmail: "aria.roberts@x.dummyjson.com",
    },

    {
      id: 49,
      productId: 132,
      userId: 1,
      rating: 2,
      comment: "Very unhappy with my purchase!",
      reviewerName: "Christopher West",
      reviewerEmail: "christopher.west@x.dummyjson.com",
    },
    {
      id: 50,
      productId: 132,
      userId: 1,
      rating: 5,
      comment: "Very happy with my purchase!",
      reviewerName: "Hazel Evans",
      reviewerEmail: "hazel.evans@x.dummyjson.com",
    },
    {
      id: 51,
      productId: 132,
      userId: 1,
      rating: 4,
      comment: "Very happy with my purchase!",
      reviewerName: "Luna Russell",
      reviewerEmail: "luna.russell@x.dummyjson.com",
    },

    {
      id: 52,
      productId: 133,
      userId: 1,
      rating: 4,
      comment: "Great value for money!",
      reviewerName: "Grace Perry",
      reviewerEmail: "grace.perry@x.dummyjson.com",
    },
    {
      id: 53,
      productId: 133,
      userId: 1,
      rating: 4,
      comment: "Highly impressed!",
      reviewerName: "Elijah Hill",
      reviewerEmail: "elijah.hill@x.dummyjson.com",
    },
    {
      id: 54,
      productId: 133,
      userId: 1,
      rating: 4,
      comment: "Would buy again!",
      reviewerName: "Eleanor Tyler",
      reviewerEmail: "eleanor.tyler@x.dummyjson.com",
    },

    {
      id: 55,
      productId: 134,
      userId: 1,
      rating: 5,
      comment: "Very pleased!",
      reviewerName: "Alice Smith",
      reviewerEmail: "alice.smith@x.dummyjson.com",
    },
    {
      id: 56,
      productId: 134,
      userId: 1,
      rating: 5,
      comment: "Great value for money!",
      reviewerName: "Harper Kelly",
      reviewerEmail: "harper.kelly@x.dummyjson.com",
    },
    {
      id: 57,
      productId: 134,
      userId: 1,
      rating: 5,
      comment: "Great product!",
      reviewerName: "Lillian Simmons",
      reviewerEmail: "lillian.simmons@x.dummyjson.com",
    },

    {
      id: 58,
      productId: 135,
      userId: 1,
      rating: 3,
      comment: "Would not recommend!",
      reviewerName: "Elijah Stewart",
      reviewerEmail: "elijah.stewart@x.dummyjson.com",
    },
    {
      id: 59,
      productId: 135,
      userId: 1,
      rating: 4,
      comment: "Great product!",
      reviewerName: "Aria Roberts",
      reviewerEmail: "aria.roberts@x.dummyjson.com",
    },
    {
      id: 60,
      productId: 135,
      userId: 1,
      rating: 4,
      comment: "Very happy with my purchase!",
      reviewerName: "Hannah Howard",
      reviewerEmail: "hannah.howard@x.dummyjson.com",
    },

    {
      id: 61,
      productId: 136,
      userId: 1,
      rating: 5,
      comment: "Highly recommended!",
      reviewerName: "Logan Lee",
      reviewerEmail: "logan.lee@x.dummyjson.com",
    },
    {
      id: 62,
      productId: 136,
      userId: 1,
      rating: 5,
      comment: "Highly recommended!",
      reviewerName: "Nolan Gonzalez",
      reviewerEmail: "nolan.gonzalez@x.dummyjson.com",
    },
    {
      id: 63,
      productId: 136,
      userId: 1,
      rating: 4,
      comment: "Fast shipping!",
      reviewerName: "Bella Grant",
      reviewerEmail: "bella.grant@x.dummyjson.com",
    },
  ]);
};
